services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-auth-service
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
#    image: mysql:5.7.34
#    container_name: mysql-db
#    platform: linux/amd64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --innodb-force-recovery=1

  migrate:
    image: migrate/migrate
    volumes:
      - ./internal/data/mysql/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "mysql://${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}",
      "up"
    ]
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data: